export const CREATE_LINK = 'CREATE_LINK';
export const DELETE_LINK = 'DELETE_LINK';

export const UPDATE_SITENAME_FIELD = 'UPDATE_SITENAME_FIELD';
export const UPDATE_URL_FIELD = 'UPDATE_URL_FIELD';

export const SITENAME_ERROR = 'SITENAME_ERROR';
export const SITENAME_EXISTS_ERROR = 'SITENAME_EXISTS_ERROR';
export const URL_ERROR = 'URL_ERROR';

export const CLEAR_SITENAME_ERROR = 'CLEAR_SITENAME_ERROR';
export const CLEAR_SITENAME_EXISTS_ERROR = 'CLEAR_SITENAME_EXISTS_ERROR';
export const CLEAR_URL_ERROR = 'CLEAR_URL_ERROR';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_WEATHER = 'FETCH_WEATHER';